---

- name: Copy RPC Ansible magnum config file
  copy: src=magnum.yml dest=/etc/openstack_deploy/conf.d mode=0644

- name: Copy RPC Ansible sahara config file
  copy: src=sahara.yml dest=/etc/openstack_deploy/conf.d mode=0644
  
- name: Copy RPC Ansible MongoDB config file
  copy: src=mongodb.conf dest=/etc/mongodb.conf mode=0644

- name: Add haproxy-install role to setup-everything playbook
  copy: src=setup-openstack.yml dest=/opt/openstack-ansible/playbooks mode=0644

- name: Copy private key to host
  copy: src=id_rsa dest=/root/.ssh mode=0600
  
- name: Copy public key to host
  copy: src=id_rsa.pub dest=/root/.ssh mode=0644

- name: Copy updated hosts file
  copy: src=hosts dest=/opt 

- name: Insert additional entries into hosts file
  shell: chdir=/opt cat /opt/hosts >> /etc/hosts

- name: Enable logging for Ansible
  shell: chdir=/opt/openstack-ansible/playbooks sed -i '1 a log_path=/var/log/ansible/ansible.log' ansible.cfg
  
- name: Create Ansible log directory
  command: mkdir /var/log/ansible

- name: Restart MongoDB service
  command: service mongodb restart