---
# This playbook deploys base environment for Openstack Icehouse. 

- hosts: infra_nodes 
  remote_user: root
  become: true
  roles:
    - access-hack
    
- hosts: compute_nodes 
  remote_user: root
  become: true
  roles:
    - access-hack

- hosts: cinder_nodes 
  remote_user: root
  become: true
  roles:
    - access-hack