---
# This playbook deploys base environment for Openstack Icehouse. 

- hosts: infra_nodes 
  remote_user: root
  become: true
  roles:
    - custom-osic-kernel
    
- hosts: compute_nodes 
  remote_user: root
  become: true
  roles:
    - custom-osic-kernel
    
- hosts: cinder_nodes 
  remote_user: root
  become: true
  roles:
    - custom-osic-kernel
