---
# This playbook deploys base environment for Openstack Icehouse. 

- hosts: control1 
  user: root
  remote_user: root
  sudo: yes
  roles:
    - network-setup

- hosts: control2 
  user: root
  remote_user: root
  sudo: yes
  roles:
    - network-setup
    
- hosts: control3 
  user: root
  remote_user: root
  sudo: yes
  roles:
    - network-setup
    
- hosts: compute1 
  user: root
  remote_user: root
  sudo: yes
  roles:
    - network-setup
    
- hosts: compute2 
  user: root
  remote_user: root
  sudo: yes
  roles:
    - network-setup
    
- hosts: compute3 
  user: root
  remote_user: root
  sudo: yes
  roles:
    - network-setup
    
- hosts: compute4 
  user: root
  remote_user: root
  sudo: yes
  roles:
    - network-setup

- hosts: compute5 
  user: root
  remote_user: root
  sudo: yes
  roles:
    - network-setup
    
- hosts: compute6 
  user: root
  remote_user: root
  sudo: yes
  roles:
    - network-setup
    
- hosts: cinder1 
  user: root
  remote_user: root
  sudo: yes
  roles:
    - network-setup
    
- hosts: cinder2
  user: root
  remote_user: root
  sudo: yes
  roles:
    - network-setup