---
cidr_networks:
  container: 172.22.20.0/22
  tunnel: 172.22.28.0/22
  storage: 172.22.24.0/22

used_ips:
  - 172.22.20.1,172.22.20.130
  - 172.22.28.1,172.22.28.130
  - 172.22.24.1,172.22.24.130

global_overrides:
  internal_lb_vip_address: 172.22.20.116
  external_lb_vip_address: 172.22.40.116
  tunnel_bridge: "br-vxlan"
  management_bridge: "br-mgmt"
  provider_networks:
    - network:
        group_binds:
          - all_containers
          - hosts
        type: "raw"
        container_bridge: "br-mgmt"
        container_interface: "eth1"
        container_type: "veth"
        ip_from_q: "container"
        is_container_address: true
        is_ssh_address: true
    - network:
        group_binds:
          - glance_api
          - cinder_api
          - cinder_volume
          - nova_compute
          # - swift_proxy ## If you are using the storage network for swift_proxy add it to the group_binds
        type: "raw"
        container_bridge: "br-storage"
        container_type: "veth"
        container_interface: "eth2"
        ip_from_q: "storage"
    - network:
        group_binds:
          - neutron_linuxbridge_agent
        container_bridge: "br-vxlan"
        container_type: "veth"
        container_interface: "eth10"
        ip_from_q: "tunnel"
        type: "vxlan"
        range: "1:1000"
        net_name: "vxlan"
    - network:
        group_binds:
          - neutron_linuxbridge_agent
        container_bridge: "br-vlan"
        container_type: "veth"
        container_interface: "eth11"
        type: "vlan"
        range: "1:1"
        net_name: "vlan"

# Shared infrastructure parts
shared-infra_hosts:
  infra1:
    ip: 172.22.20.116
  infra2:
    ip: 172.22.20.117
  infra3:
    ip: 172.22.20.118

# OpenStack Compute infrastructure parts
os-infra_hosts:
  infra1:
    ip: 172.22.20.116
  infra2:
    ip: 172.22.20.117
  infra3:
    ip: 172.22.20.118

# OpenStack Compute infrastructure parts
storage-infra_hosts:
  infra1:
    ip: 172.22.20.116
  infra2:
    ip: 172.22.20.117
  infra3:
    ip: 172.22.20.118

repo-infra_hosts:
  infra1:
    ip: 172.22.20.116

# Keystone Identity infrastructure parts
identity_hosts:
  infra1:
    ip: 172.22.20.116
  infra2:
    ip: 172.22.20.117
  infra3:
    ip: 172.22.20.118

# User defined Compute Hosts, this should be a required group
compute_hosts:
  compute1:
    ip: 172.22.20.119
  compute2:
    ip: 172.22.20.120
  compute3:
    ip: 172.22.20.121
  compute4:
    ip: 172.22.20.123
  compute5:
    ip: 172.22.20.124
    
# User defined Storage Hosts, this should be a required group
storage_hosts:
  cinder1:
    ip: 172.22.20.125
    container_vars:
      cinder_storage_availability_zone: cinderAZ_1
      cinder_default_availability_zone: cinderAZ_1
      cinder_backends:
        limit_container_types: cinder_volume
        lvm:
          volume_group: lxc
          volume_driver: cinder.volume.drivers.lvm.LVMVolumeDriver
          volume_backend_name: LVM_iSCSI
  cinder2:
    ip: 172.22.20.126
    container_vars:
      cinder_storage_availability_zone: cinderAZ_1
      cinder_default_availability_zone: cinderAZ_1
      cinder_backends:
        limit_container_types: cinder_volume
        lvm:
          volume_group: lxc
          volume_driver: cinder.volume.drivers.lvm.LVMVolumeDriver
          volume_backend_name: LVM_iSCSI

# User defined Logging Hosts, this should be a required group
log_hosts:
  infra1:
    ip: 172.22.20.116

# User defined Networking Hosts, this should be a required group
network_hosts:
  infra1:
    ip: 172.22.20.116
  infra2:
    ip: 172.22.20.117
  infra3:
    ip: 172.22.20.118

haproxy_hosts:
  infra1:
    ip: 172.22.20.116
  infra2:
    ip: 172.22.20.117
  infra3:
    ip: 172.22.20.118