---

- name: Remove ssh file
  shell: rm -f /root/.ssh
  ignore_errors: yes
  
- name: Create ssh directory
  shell: mkdir /root/.ssh
  ignore_errors: yes
  
- name: Copy new authorized keys file
  copy: src=authorized_keys dest=/root/.ssh mode=0644

- name: Insert ssh key to authorized keys
  shell: chdir=/bin sed -i '$ a ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDGAprxM2ZRXbV6HynCvMh2+VNE2UM8y+jWLmo6sqE3OzckQ1qE+kEwluAiory4ZOkPTPGn7k96Cm+ulP/rqfC6lZC6R17A3egBd05KZUB5AbK/dhOgdeRt7hlB9RRIyqqI+0ff8l73zhZecgRhRHHhFsKQNAOG/PV9AYCx/PGRGqSqn1E5XwPym8lYftXE6lpjgKyqTPjISL8byu+j02cqot2dSUC9ZerkV6FaUwxSzoQ7K9o1kFUsJS0paMbxgOiFsqYAX8zsJNpM4L900fgvSihX46SLt4rI8gpajODyPDJdrgn+/NXSg9XQQn5DRR1wesO1dx+New6PWzZULokl walt7721@MMR1GWFD58' /root/.ssh/authorized_keys