---

- name: IPv6 DNS fix
  copy: src=99force-ipv4 dest=/etc/apt/apt.conf.d

- name: Fix OSIC DNS
  shell: echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf > /dev/null
  
- name: Install apt-get updates
  command: apt-get update
  
- name: Upgrade via apt-get
  command: apt-get -q -y upgrade

- name: Install additional packages
  apt: name={{item}} state=present
  with_items:
   - bridge-utils
   - lsof
   - lvm2
   - openssh-server
   - sudo
   - tcpdump
   - vlan
   - vim
   - ifenslave-2.6
  
- name: Enable interface bonding
  copy: src=modules dest=/etc
  
- name: Enable bonding kernel module
  command: modprobe bonding
  
- name: Copy updated hosts file
  copy: src=hosts dest=/opt
  
- name: Copy public key to host
  copy: src=id_rsa.pub dest=/root/.ssh mode=0644
